version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beauty_salon_bot
    command: python -m src.bot.main
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - DB_HOST=postgres

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beauty_salon_api
    command: python /app/run_api.py
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - DB_HOST=postgres

  postgres:
    image: postgres:15
    container_name: beauty-salon-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=beauty_salon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
